repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust code using rustfmt
        entry: cargo fmt --all
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        description: Run clippy on Rust code
        entry: cargo clippy -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false