[package]
name = "lictl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true } 
dialoguer = "0.11.0"
keyring = "3.6.2"
serde = { workspace = true }
tokio = { workspace = true }
